### ISSUE TITLE
Feature issue (Fix text alignment)

### ISSUE THREAD

**Issue by Mustafabd** [info442-su23/f-team#80]
- The text should be centered so that it can be easier to read
- This will make the page easier to navigate
<img width="1111" alt="image" src="https://github.com/info442-su23/f-team/assets/80429899/5e822ff6-2dd9-47af-9cf6-32c8317265d2">

**Comment by EloraHob** [comment]
Unable to reproduce" navigating to the homepage displays article image correctly. 

<img width="738" alt="Screenshot 2023-08-10 at 4 54 49 PM" src="https://github.com/info442-su23/f-team/assets/104376570/f9fa3622-d52b-47b1-8fd2-fdd37cca3b0f">
