### ISSUE TITLE
Search only works for initial search - Bug Major

### ISSUE THREAD

**Issue by elisabeth-h7** [info442-su23/f-team#82]
When you first search it comes up with results, but if you hit search again or try to search a new medication it says "no results found." The "apply filter" also didn't change the results. 

Mac OS Catalina, Chrome 

Steps to reproduce:
- search "tylenol" in medication
- results come up and select filters
- click apply filters 
- click search again 
- (this also occurred without applying any filters and just clicking the search button twice, had to reload page and search again for results to pop up)

Expected: results based on filter, or same search results 
Received: "no results found" message 

<img width="1426" alt="Screen Shot 2023-08-08 at 5 41 33 PM" src="https://github.com/info442-su23/f-team/assets/62919487/697af37f-2b1b-4b9c-a30d-2ca9b8a8e9ed">

**Comment by sloaneshea** [comment]
additional information:
also, the search bar from the homepage does not link to anything. Would be nice if this feature could link to the separate js pages at least

**Comment by EloraHob** [comment]
I was unable to reproduce this bug. 

Steps taken: 

Search "Tylenol" and press the search button. (5+ results appear)
Select "capsule" and press "apply filters" button.
Press search button. (Only 2 results appear)
