### ISSUE TITLE
Feature request - homepage cards inactive state

### ISSUE THREAD

**Issue by vuongb2** [info442-su23/f-team#83]
I don't think there is a point to making the cards on the homepage hover -- it would be more convenient to have them exist as full cards all the time. It's unclear that you can even hover over them for additional information.

![image](https://github.com/info442-su23/f-team/assets/114948475/bd4af70d-688d-4c00-b8cb-90891f3cd4e5)

**Comment by haonanzzz** [comment]
The hover features is on our design, but will take it into consideration
