### ISSUE TITLE
Mobile Design is Hard to Navigate - Feature Request

### ISSUE THREAD

**Issue by taylor-russon** [info442-su23/f-team#84]
I am using a iPhone 13 iOS Version 16.6 on Safari and to navigate the pages it requires a lot of zooming in and out. You can't see many of the features and text unless you know to zoom out. 

![IMG_2BEB7C4A6826-1](https://github.com/info442-su23/f-team/assets/91644521/0d1d2871-97a5-4782-acc2-4ba2b2c66af7)
![IMG_1845F4E6D04A-1](https://github.com/info442-su23/f-team/assets/91644521/8dfc42da-85fb-4f21-9f31-c74b6b16ac62)

**Comment by haonanzzz** [comment]
The avalibility for mobile is not on our requirement
