### ISSUE TITLE
Feature request - usability of every features search bar

### ISSUE THREAD

**Issue by vuongb2** [info442-su23/f-team#85]
It is very difficult for users to actually remember the names of the drugs they use, especially old people, who may be using this the most. Even if I search "ibprfn", which is ibuprofen without any vowels, it can't bring up any results. There is also no combo box / drop down menu, which would be very helpful for users.

![image](https://github.com/info442-su23/f-team/assets/114948475/46868a84-e67e-4d4f-a1fa-2db6003a6b29)

**Comment by EloraHob** [comment]
Our API already includes close-match results when applicable, but we may want to consider drop down results on Filter page.
