### ISSUE TITLE
Homepage Button No action; Severity: Major

### ISSUE THREAD

**Issue by MarinaCui** [info442-su23/f-team#86]
Summary: On We make it easier for you section, the three quick button links don't take me anywhere.
Environment: Chrome 115.0.5790.170 on macOS Ventura 13.4
Steps to Reproduce: Homepage -> scroll down to the bottom -> click on one of the buttons -> no action
Expected Result: Take me to the corresponding feature page
Actual Result: No action

**Comment by haonanzzz** [comment]
This is a duplicate one, we will fix it

#81

**Comment by haonanzzz** [comment]
This is a duplicate one, we will fix it

#81
