### ISSUE TITLE
Minor Bug: Image alt text showing up, doubled images on social media toolkit page

### ISSUE THREAD

**Issue by sloaneshea** [info442-su23/f-team#87]
1. minor bug
2. some repeat images and alt caption being shown below image
3. Chrome Version 115.0.5790.114 (Official Build) (x86_64)
4. social media toolkit in footer, see images
5. not repeat images, the actual word "alt" not showing up
6. just that
7. 
<img width="501" alt="Screen Shot 2023-08-08 at 8 47 14 PM" src="https://github.com/info442-su23/f-team/assets/77075019/72393920-e165-4aa7-8e09-a2781b409150">

**Comment by EloraHob** [comment]
Unable to reproduce. 

Steps taken: 

Search 'wellbutrin' in search bar and click search.
Select first medication card result.
Redirected to this page: 

<img width="1085" alt="Screenshot 2023-08-10 at 5 14 47 PM" src="https://github.com/info442-su23/f-team/assets/104376570/f6f1c25e-51b4-4f5f-a3ab-d86a34898da6">
