### ISSUE TITLE
Medication search results duplicate and inactive (Minor bug)

### ISSUE THREAD

**Issue by FastFusion5** [info442-su23/f-team#88]
I was checking out the filter function for the medication and the search results are duplicate and inactive. It would be nice to make them active so I could learn more about each medication (What it is for, how to take it etc.) Currently, I don't know much about the medication just from its name and manufacturer. I am using Safari 16.3 on Mac.
<img width="1512" alt="Screenshot 2023-08-09 at 8 44 37 AM" src="https://github.com/info442-su23/f-team/assets/77070825/2a708fd8-b210-46ef-ae66-1c1be4afeee7">

**Comment by EloraHob** [comment]
Medications are not duplicate, but drug dose could be displayed to more clearly indicate difference between cards, and connect results to MedlinePlus API to display more information.
