### ISSUE TITLE
Medication Search autocomplete; Feature Request

### ISSUE THREAD

**Issue by MarinaCui** [info442-su23/f-team#90]
Summary: On `Search Medication` section, it will be confusing if the users don't know exactly what the medication is called.
Environment: Chrome 115.0.5790.170 on macOS Ventura 13.4
Steps to Reproduce: Homepage -> Search -> search bar -> no autocomplete
Expected Result: Provide me with some items to select
Actual Result: Plain text in the search bar

**Comment by EloraHob** [comment]
Consider implementing autocomplete for search bar
