### ISSUE TITLE
Cannot apply multiple filters - Bug Minor

### ISSUE THREAD

**Issue by sjhu2020** [info442-su23/f-team#92]
When I attempt apply a single filter to a search, it does what I expect and display all medications that match my search.  However, when I try to apply a different filter that doesn't match any of the medication, hit apply, and search, I don't get any results.  I expected to get the same results from my previous search, as the second filter shouldn't remove anything.  If I unselect the second filter and apply again it works so there is a workaround, however in the future the filter should be able to account for multiple filter options without conflicts.

Steps to reproduce:
1. Search 'tylenol'
2. Select 'Oral' filter
3. Hit search

<img width="1276" alt="image" src="https://github.com/info442-su23/f-team/assets/74697916/40fbad6d-fe58-4351-b8cc-cd3d0212e3a5">

4. Select 'Topical' filter
5. Hit search, no results found

<img width="1266" alt="image" src="https://github.com/info442-su23/f-team/assets/74697916/e0e5ced9-428d-428b-b247-102241c03453">

**Comment by haonanzzz** [comment]
duplicate with#91
