### ISSUE TITLE
Feature Request: Make these cards of the drugs link to the other informative description of the drugs

### ISSUE THREAD

**Issue by ryo884-2177391** [info442-su23/f-team#95]
<img width="1437" alt="Screenshot 2023-08-08 at 6 00 05 PM" src="https://github.com/info442-su23/f-team/assets/92127242/eca538d6-eb80-4bdc-8bc8-8b78e9921825">
I can understand it should be so challenging to implement this search engine that can meet every user's request :(
Since other classmates commented these main bugs, I just want to mention about the feature request that you guys may be able to let these cards of the drugs link to the other informative description of the drugs. Then, users will be able to learn more the detailed in these drugs and get more educated.

**Comment by EloraHob** [comment]
Results should be clickable and work similarly to search page results linking to MedlinePlus api pages.
