### ISSUE TITLE
Bug Major - Search Bar on Home page has no search function

### ISSUE THREAD

**Issue by phyllisUW** [info442-su23/f-team#96]
Major Bug
When I try to search anything relevant to this web app such as any the word medication, or medication names, or any of the features offered in this web app, nothing happens and there are no suggestions that pop up. The function for this search bar is unclear.
Encountered on Microsoft Edge (Version 115.0.1901.188)
Reproduce search bar function in main home page
Expected: suggestion to pop up when opening search bar, feature suggestions, any elements to appear for redirect after search 
Actual: I cannot search for anything relevant to page
<img width="275" alt="image" src="https://github.com/info442-su23/f-team/assets/91918592/d9410e8c-218b-4ce7-80ec-1ded9d164021">

**Comment by EloraHob** [comment]
The function/existence of this search bar is not included as a requirement in our requirements.md specifications.

**Comment by DongTianjia** [comment]
Hi Phyllis, the search feature within our nav bar is intended to search for medication names, and it functions just like our search page search feature. For example, if you search "Advil" in the top search bar, and clicks on the search button, it will automatically take you to the "Just Search" page with Advil results populated on the page (see screenshot below). Maybe it wasn't clear for the users, but you cannot search site-wide info, like features offered in this web app. It should not be a bug, but we can definitely improve on it by maybe indicating "Search for a medication name" within the search bar. 
<img width="1280" alt="Screen Shot 2023-08-10 at 14 53 49" src="https://github.com/info442-su23/f-team/assets/87292522/3e550829-54f6-4242-86b7-871feaa9da1f">
