### ISSUE TITLE
Minor bugs: Footer not at bottom when no result found

### ISSUE THREAD

**Issue by VictoriaVVei** [info442-su23/f-team#98]
Summary: Footer not at bottom when no result found
Environment: Chrome on Win 11 (Version 115.0.5790.171)
Steps to reproduce: After search for a key word, the footer will change from to bottom to middle of the page
Expected result: Footer always at bottom.
Actual result: Footer change position.
Attachments:
![60c07e51f25d389c89bfe3db5d7b3cf](https://github.com/info442-su23/f-team/assets/91993339/e9cbe000-f2f7-4edb-85f5-74328c69675d)

**Comment by EloraHob** [comment]
This is not a bug, but we will consider including empty whitespace on page.
